# Generated by Django 5.2.4 on 2025-07-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='ID de Usuario')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('completed', models.BooleanField(default=False, verbose_name='¿Completado?')),
            ],
        ),
    ]
